dist: trusty  # need Ubuntu >= 14
sudo: required
language: python

python:
    # - "3.2"
    - "3.4"
    - "3.5"

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get update
    - ./bootstrap-debian.sh

install:
    - ./install.py
    - ./install.py --uninstall=virtualenv

script:
    - ./install.py --checks --tests
